project:
  type: website
  output-dir: docs

toc: true

execute: 
  freeze: auto

website:
  title: "2025 URSSI Summer School on Research Software and Open Science"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - software_design.ipynb
      - package_structure.ipynb
      - package_distribution.ipynb
      - collaboration.ipynb
      - testing.ipynb
      - peer_code_review.ipynb
      - documentation.ipynb
      - open-science.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
